<h1 id="chrome-debugger">Chrome Debugger<a aria-hidden="true" class="anchor-heading icon-link" href="#chrome-debugger"></a></h1>
<h2 id="debugging-outbound-network-issues">Debugging outbound network issues<a aria-hidden="true" class="anchor-heading icon-link" href="#debugging-outbound-network-issues"></a></h2>
<ol>
<li>Sources tab, hit <code>Pause on exceptions</code> (stop sign with pause icon)</li>
<li>Reload the page, and code will pause on the first exception that happens</li>
<li>Hover over the failing line, and investigate
<ul>
<li>are args to the function call what you'd expect them to be? Does anything stand out? Why is an error being thrown?</li>
</ul>
</li>
</ol>